{
  "port": 8080,
  "HOST": "127.0.0.1",
  "mongodbOption": {
    "url": 'mongodb://39.98.215.216:30003',
    "options": {
      useNewUrlParser: true
    },
    "dbName":'xwys-test'
  },
  "redisOption": {
    "host": "39.98.215.216",
    "port": "30007",
    "password": 123456,
    "db": "xwys-test",
  },
  "reptileZxMovieUrl": {
    "wangzherongyao":{
      "list": "https://mzdy.tbhmdk.com/app/film-list?page=0&classifyKey=",
      "search": "https://mzdy.tbhmdk.com/app/video/search?name=",
      "filmDetail": "https://mzdy.tbhmdk.com/app/film/",
      "teleplayDetail": "https://mzdy.tbhmdk.com/app/teleplay/"
    },
    "xigua": "https://mzdy.tbhmdk.com/app/film-list?page=0&classifyKey=ZX",
    "xiaoxiaoys":{
      "list":"https://sk4848y8b6qkymisc57n.xiaoxiaoimg.com/index?tab=0&apiVersion=28&deviceModel=SM-G9500&brand=samsung&deviceName=dreamqltechn&serial=988ed5375952443333&platform=android"
        "seach":"https://sk4848y8b6qkymisc57n.xiaoxiaoimg.com/search?page=1&wd=",
      "getdetail":"https://sk4848y8b6qkymisc57n.xiaoxiaoimg.com/vod/show/",
      "getM3u8":"https://sk4848y8b6qkymisc57n.xiaoxiaoimg.com/vod/reqplay/",
      "viewRankList":"https://android.xiaoxiaoapps.com/vod/day-"
    }
  },
  "winston": {
    "application": "xyws-01-local",
    "transports": {
      "LogstashTransport": {
        "host": "log.mo",
        "port": 60201
      }
    }
  }
}
