{
  "port": 3001,
  "HOST": "127.0.0.1",
  "mongodbOption": {
    "url": 'mongodb://47.111.28.42:30003',
    "options": {
      useNewUrlParser: true
    },
    "dbName":'xwys-test'
  },
  "redisOption": {
    "host": "47.75.73.120",
    "port": "30007",
    "password": 123456,
    "db": "xwys-test",
  },
  "reptileZxMovieUrl": {
    "wangzherongyao": "https://mzdy.tbhmdk.com/app/film-list?page=0&classifyKey=",
    "wangzherongyaoSearch": "https://mzdy.tbhmdk.com/app/video/search?name=",
    "wangzherongyaoDetail": "https://mzdy.tbhmdk.com/app/film/",
    "xigua": "https://mzdy.tbhmdk.com/app/film-list?page=0&classifyKey=ZX",
    "xiaoxiaoys":{
      "list":"https://android.xiaoxiaoapps.com/index?tab=0",
      "seach":"https://android.xiaoxiaoapps.com/search?wd=",
      "getdetail":"https://android.xiaoxiaoapps.com/vod/show/",
      "getM3u8":"https://android.xiaoxiaoapps.com/vod/reqplay/"
    }
  },
  "winston": {
    "application": "xyws-01-local",
    "transports": {
      "LogstashTransport": {
        "host": "log.mo",
        "port": 60201
      }
    }
  }
}
